// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// CarColumns holds the columns for the "car" table.
	CarColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "user_id", Type: field.TypeInt64, Nullable: true},
		{Name: "model", Type: field.TypeString, Nullable: true},
		{Name: "registered_at", Type: field.TypeTime, SchemaType: map[string]string{"mysql": "datetime"}},
	}
	// CarTable holds the schema information for the "car" table.
	CarTable = &schema.Table{
		Name:       "car",
		Columns:    CarColumns,
		PrimaryKey: []*schema.Column{CarColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		CarTable,
	}
)

func init() {
	CarTable.Annotation = &entsql.Annotation{
		Table: "car",
	}
}
